### ISSUE TITLE
在Cordova中调用Flutter方法 

### ISSUE THREAD

**Issue by guircoelho** [waitaction/cordova-plugin-flutter#5]
如何在cordova内部的flutter模块中调用方法？无需打开Flutter应用 

谢谢 

---

How can I call a method inside flutter module inside the cordova? Without opening the Flutter App

Thank you

**Comment by AndreNeves97** [comment]
Hi @guircoelho 
You need to add more methods aside `init` and `open` in file https://github.com/waitaction/cordova-plugin-flutter/blob/master/www/cordova-plugin-flutter.js

You also need handle this methods call in iOS and Android Files: https://github.com/waitaction/cordova-plugin-flutter/blob/master/src/ios/CDVFlutter.m and https://github.com/waitaction/cordova-plugin-flutter/blob/master/src/android/com/flutter/android/FlutterCordovaPlugin.java

What are you needs? Maybe I'll use this plugin in the next months, so I'll need to make some changes to use in my project

**Comment by guircoelho** [comment]
Hello @AndreNeves97! Thanks for your response. We abandoned the idea, it was very complicated to manage. Good luck!
